# Generated by Django 4.1.4 on 2022-12-16 03:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_publicacion', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
